#!/bin/bash

filechk() {
if [ -e $1 ] ; then
    echo $1 exists 
    if [ -f $1 ]; then
       echo $1 reaglar file
#    elif [ -d $1 ]; then
#        echo $1 is a directory
    elif
#        echo $1 exists nonfile/nondirectory
    fi
else
    echo $1 does not exist
fi
}
filechk /home/rchansen/.local/bin/$1
filechk /home/rchansen/bin/$1
filechk /home/rchansen/bin/f
filechk /home/rchansen/bingit/$1
