#!/usr/bin/env bash
# compare bin and mybin directories  excluding fom files
# f_acrolist  - list of file/acronym connections for  f
# gnamelist   - list of files for g 
# grdirnamelist - output of grdir (grep-ing wihin a directory
# grmelist  - list of files to grep against	
# tempname  - place where I write scractch oufput of cmds
# cdit  -  contains a list of directory to cd to by acro
# g2namelist 
savdir=$PWD
cd
diff bin mybin -x f_acrolist -x gnamelist -x grdirnamelist -x grmelist -x tempname -x cdit -x filedump -x g2namelist > ~/tempname
diff -s .profile mybin/.profile >> ~/tempname
diff -s .bashrc mybin/.bashrc >> ~/tempname
diff -s .bash_aliases mybin/.bash_aliases >> ~/tempname
diff -s .vimrc mybin/.vimrc >> ~/tempname
diff -s .bin/colors/mine.vim  mybin/mine.vim  >> ~/tempname
vim ~/tempname
cd $savdir
