#!/usr/bin/env bash

# compare a file with what is in raspbin
# method
#   cd desired dir
#   diffras desired-mem
xbin="raspbin"
if ! [ -f $xbin ]; then 
  xbin="mybin"
fi
# check to see if they exist
both_files=true
if ! [ -f $1 ]; then
  echo "$1 not in $PWD"
  both_files=false
fi

if ! [ -f ~/$xbin/$1 ]; then
  echo "$1 not in ~/$xbin"
  both_files=false
fi  

if [ $both_files = false ]; then 
  echo "Sombody missing, I quit! "
  exit 4
fi

diff $1 ~/$xbin/$1
diffrc=$?
if [ ".$diffrc" == ".0" ]; then
   echo "$PWD/$1 and ~/$xbin/$1 are the SAME"
else
   echo "$PWD/$1 and ~/$xbin/$1 are the UNEQAL  -- check above"
fi
