#!/bin/bash

#  Below is the acro file (name of acro filename action    file )
file_input=$HOME"/bin/f_acrolist"

p1=$1       # save cmdline parms for later
p2=$2

#  Help info
if [ ".$1" == "." ] ; then
  echo ":::::::::::::::::::::::::::::::::::::::::::::::::::"
  echo "::  f -  quick invocation to file                ::"
  echo "::  f parm1 parm2                                ::"
  echo "::    parm1                                      ::"
  echo "::      null   - display this help info          ::"
  echo "::      .      - go edit the acro list file      ::"
  echo "::      other  - acro for filename in file_input ::"
  echo "::    parm2    - action to take default vim      ::"
  echo "::               if sudo ->  sudo vim parm1      ::"
  echo "::                                               ::"
  echo ":: format of acro file    3 values               ::"
  echo "::   field1 acro  the acronym to search for      ::"
  echo "::   field2 filename to act upon                 ::"
  echo "::   field3 action to take  null  vim            ::"
  echo "::    (more info in the acro file itself.)       ::"
  echo ":::::::::::::::::::::::::::::::::::::::::::::::::::"
  exit 
fi

# path to the acro file
if [ ".$1" == ".." ] ; then    # use  f .  to get to the acro file
  vim $file_input
  exit
fi


found="no"   

#  if null-line skip it
#     if char1 of acro is #  skip it
#        if passed-val is acro  mark found and bail to work

while  read -r acro filename action rest ; do
  if [ "." != ".$acro" ]; then
    if [ ${acro:0:1}  != "#" ]; then
      if [ "$1" == "$acro" ] ; then
        found="yes"
        echo "matched acro : "$acro", filename :" $filename", action :"$action
        break                                # the quick out when found
      fi
    fi 
  fi
done < $file_input       # end read loop from given file_input

# NOT found msg and exit
if [ "$found" == "no" ] ; then
  echo "::                                               "
  echo ::  acronym  $1  NOT found try . for acrolist 
  echo "::                                               "
  exit
fi

cmd_action=""                       # unknow what to do
# handling sudo on cmdline  to empower f   
sudoit=""                          # defaulting sudoit to null
if [ ".$p2" == ".sudo" ] ; then     # found on original cmd line
  sudoit="sudo"
fi

# evaluate for cmd_action value
# parm 2 in cmdline supercedes

if [ ".$p2" != ".sudo" ] && [ ".$p2" != "." ] ; then   
  cmd_action=$p2 
fi

# Setting the command  action from line in file_input
#  remember cmdline parm 2 supercedes (if not sudo)
if [ ".$cmd_action" == "." ]; then        # cmd_action not set yet
  if [ ".$action" == "." ] ; then
    cmd_action=vim                    # the default
  else
    cmd_action=$action                # the override
  fi  
fi
 

# The actual work

# Handle ~/whoever   to become     /home/$USER/whoever
if [ ${filename:0:1} == "~" ] ; then
# if [ ".$UID" == ".0" ] ; then     # the root case
#   lead="/root"
# else
#   lead="/home/"$USER      #  non root user
# fi

  lead=$HOME              # now is /home/$USER   or   /root
  tailend=${filename:1}   # peel off the ~
  filename=$lead$tailend  # provide actual name 
  #echo $filename          # show on screen (just in case)
fi

# handle action being sudo
if [ ".$action" == ".sudo" ]; then
  sudoit="sudo"
  cmd_action="vim"
fi

#echo "sudoit :"$sudoit 
#echo "filename :"$filename
#echo "cmd_action :"$cmd_action
echo $sudoit $cmd_action $filename
$sudoit $cmd_action $filename            # the actual work

