#!/usr/bin/env bash

# newcessary for this to work
# script gg - this guy
# script g1 - modified version of g 
# directory ~/bin/g_acrolist_dir - directory containing list
# file ~/bin/g_acroname  - file contain member
# file ~/bin/g1_acrolist - default g1 file

# insure file with name of acrolist exists
has_acrolist=$HOME/bin/g_acroname  # file containing name in  sub-dir 
   # g_acrolist_dir   If this is empty use ~/bin/g_acrolist

if  [ -f $has_acrolist ]; then
    echo $has_acrolist" exists.  yea!"
  else
    echo "Creating "$has_acrolist
    touch $has_acrolist    # contains list of acro-s in ~/bin/g_acros
  fi


if [ ".$1" == "." ]; then
  echo "Activate/Inactivate the name of the acronyn file"
  echo "found in directory ~/bin/g_acrolist_dir"
  echo " on  - prompts for the name"
  echo " off - clears the filename "
  echo " null - display help and filename"
  echo "  .   - vim to the acrofile_name"
  echo " other - act like g  up to three parms"
  echo " "
# fi
# nl=`wc $HOME/bin/g_acroname |  awk '{print $1}'`
  nl=`wc $has_acrolist |  awk '{print $1}'`

  acroname=""
  if [ ".$nl" == ".0" ]; then
    echo $has_acrolist " is NULL"
  else
    acroname=`head -n1 $has_acrolist | tail -n1`
    echo "$HOME/bin/g_acrolist_dir/"$acroname "is the list to search."
  fi
  exit
fi
p1=$1
if [ ".$p1" == ".off" ]; then 
  p1="OFF"
fi

if [ ".$p1" == ".OFF" ]; then 
  rm $has_acrolist
  sleep 1
  touch $has_acrolist
#  nl=`wc $HOME/bin/acrofile_name`
#  echo  $nl $nl
  exit 
fi


if [ ".$p1" == ".on" ]; then
  p1="ON" 
fi

if [ ".$p1" == ".ON" ]; then 
   echo -n "Enter the acroparm file name : "
   read answer   rest
   acroparm=$answer 
#  echo $acroparm
   echo $acroparm   $has_acrolist  
   echo $acroparm > $has_acrolist
   echo "Using 2>"$acroparm"< for acro list name."
   cat $has_acrolist
   exit
fi
#echo acroparm is ">"$acroparm <"

echo go do g1 $1 $2 $3
g1 $1 $2 $3
