#!/bin/bash

filechk() {
if [ -e $1 ] ; then
    if [ -f $1 ]; then
       echo $1 reaglar file
    else
#      echo $1 non regular
       if [ -d $1 ]; then
         echo $1 is a directory
       else
         echo $1 exists nonfile/nondirectory
       fi
    fi
else
    echo $1 does not exist
fi
}
filechk /home/rchansen/.local/bin
filechk /home/rchansen/bin
filechk /home/rchansen/bin/f
filechk /home/rchansen/bingit/$1
